# Generated by Django 2.0.4 on 2018-04-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='novel_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('writter', models.CharField(max_length=100)),
                ('pub', models.CharField(max_length=1000)),
                ('pub_date', models.CharField(max_length=1000)),
                ('price', models.FloatField()),
                ('rating', models.IntegerField()),
                ('rating_nums', models.IntegerField()),
            ],
        ),
    ]
