# Generated by Django 2.0.4 on 2018-04-27 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qidian_Xiaoshuo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novel_name', models.CharField(max_length=100)),
                ('novel_writter', models.CharField(max_length=100)),
                ('novel_main_type', models.CharField(max_length=100)),
                ('nvoel_sub_type', models.CharField(max_length=100)),
                ('novel_status', models.CharField(max_length=100)),
                ('novel_img_save_path', models.CharField(max_length=100)),
                ('novel_chapter_save_path', models.CharField(max_length=100)),
                ('novel_chapter_name', models.CharField(max_length=100)),
                ('novel_img_url', models.CharField(max_length=100)),
                ('novel_real_url', models.CharField(max_length=100)),
            ],
        ),
    ]
