# Generated by Django 2.0.4 on 2018-04-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qidian', '0003_auto_20180428_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter_Detail_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novel_name', models.CharField(max_length=100)),
                ('novel_chapter_name', models.CharField(max_length=100)),
                ('novel_chapter_url', models.CharField(max_length=100)),
                ('novel_chapter_path', models.CharField(max_length=100)),
                ('novel_chapter_id', models.IntegerField()),
            ],
        ),
    ]
