# Generated by Django 2.0.4 on 2018-05-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qidian', '0004_chapter_detail_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter_detail_table',
            name='novel_chapter_path',
        ),
        migrations.AddField(
            model_name='chapter_detail_table',
            name='chapter_update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chapter_detail_table',
            name='novel_chapter_context',
            field=models.TextField(default=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qidian_xiaoshuo',
            name='novel_update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='qidian_xiaoshuo',
            name='novel_img_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='qidian_xiaoshuo',
            name='novel_real_url',
            field=models.URLField(),
        ),
    ]
